import { City, Hotel, Package, User, Inquiry, Review } from '../types.js';
import bcrypt from 'bcryptjs';

export async function getInitialSeedData() {
  const adminPasswordHash = await bcrypt.hash('Admin@123', 10);
  const userPasswordHash = await bcrypt.hash('User@123', 10);

  const users: (User & { password?: string })[] = [
    {
      id: 'usr-admin-1',
      name: 'Enterprise Yatra Admin',
      email: 'admin@tirthyatratrails.com',
      password: adminPasswordHash,
      role: 'ADMIN',
      createdAt: '2026-01-10T08:00:00.000Z',
    },
    {
      id: 'usr-admin-2',
      name: 'Executive Yatra Admin',
      email: 'admin@tirthyatra.com',
      password: adminPasswordHash,
      role: 'ADMIN',
      createdAt: '2026-01-10T08:00:00.000Z',
    },
    {
      id: 'usr-demo-1',
      name: 'Rohan Sharma',
      email: 'rohan.sharma@example.com',
      password: userPasswordHash,
      role: 'USER',
      createdAt: '2026-02-15T10:30:00.000Z',
    },
  ];

  const cities: City[] = [
    {
      id: 'city-varanasi',
      name: 'Varanasi',
      state: 'Uttar Pradesh',
      popularFor: 'Kashi Vishwanath & Ganga Aarti',
      imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
      hotelCount: 38,
    },
    {
      id: 'city-ayodhya',
      name: 'Ayodhya',
      state: 'Uttar Pradesh',
      popularFor: 'Shri Ram Janmabhoomi & Saryu River',
      imageUrl: 'https://images.unsplash.com/photo-1706857053427-4c3e8006bbca?auto=format&fit=crop&w=800&q=80',
      hotelCount: 24,
    },
    {
      id: 'city-kedarnath',
      name: 'Kedarnath',
      state: 'Uttarakhand',
      popularFor: 'Kedarnath Jyotirlinga & Himalayas',
      imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
      hotelCount: 19,
    },
    {
      id: 'city-rishikesh',
      name: 'Rishikesh & Haridwar',
      state: 'Uttarakhand',
      popularFor: 'Yoga Capital & Sacred Har Ki Pauri',
      imageUrl: 'https://images.unsplash.com/photo-1600100397608-f010f443bbf6?auto=format&fit=crop&w=800&q=80',
      hotelCount: 42,
    },
    {
      id: 'city-tirupati',
      name: 'Tirupati',
      state: 'Andhra Pradesh',
      popularFor: 'Lord Sri Venkateswara Swamy Temple',
      imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
      hotelCount: 31,
    },
    {
      id: 'city-puri',
      name: 'Puri',
      state: 'Odisha',
      popularFor: 'Lord Jagannath Mandir & Golden Beach',
      imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
      hotelCount: 29,
    },
    {
      id: 'city-rameshwaram',
      name: 'Rameshwaram',
      state: 'Tamil Nadu',
      popularFor: 'Ramanathaswamy Jyotirlinga & Ram Setu',
      imageUrl: 'https://images.unsplash.com/photo-1621847468516-1ed5d0df56fe?auto=format&fit=crop&w=800&q=80',
      hotelCount: 22,
    },
    {
      id: 'city-dwarka',
      name: 'Dwarka & Somnath',
      state: 'Gujarat',
      popularFor: 'Dwarkadhish Temple & 1st Jyotirlinga',
      imageUrl: 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=800&q=80',
      hotelCount: 26,
    },
    {
      id: 'city-vrindavan',
      name: 'Mathura & Vrindavan',
      state: 'Uttar Pradesh',
      popularFor: 'Banke Bihari & Prem Mandir',
      imageUrl: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=800&q=80',
      hotelCount: 35,
    },
    {
      id: 'city-shirdi',
      name: 'Shirdi',
      state: 'Maharashtra',
      popularFor: 'Sai Baba Samadhi Mandir',
      imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80',
      hotelCount: 28,
    },
    {
      id: 'city-ujjain',
      name: 'Ujjain',
      state: 'Madhya Pradesh',
      popularFor: 'Mahakaleshwar Jyotirlinga & Bhasma Aarti',
      imageUrl: 'https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=800&q=80',
      hotelCount: 20,
    },
    {
      id: 'city-amritsar',
      name: 'Amritsar',
      state: 'Punjab',
      popularFor: 'Sacred Harmandir Sahib (Golden Temple)',
      imageUrl: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=800&q=80',
      hotelCount: 34,
    },
  ];

  const hotels: Hotel[] = [
    {
      id: 'htl-varanasi-1',
      cityId: 'city-varanasi',
      cityName: 'Varanasi',
      name: 'BrijRama Palace - Heritage Grand on Darbhanga Ghat',
      starRating: 5,
      googleRating: 4.9,
      reviewCount: 1420,
      address: 'Darbhanga Ghat, Dashashwamedh, Varanasi, Uttar Pradesh 221001',
      distanceToTemple: '350m from Kashi Vishwanath Corridor',
      darshanType: 'Private VIP Boat to Temple Ghat',
      description: 'One of the oldest structures on the sacred Ganga ghats dating back to the 18th century. BrijRama Palace offers unrivaled spiritual luxury with private morning Mangala Aarti boat transfers, classical thumri live recitals in the Bada Aangan atrium, and pure vegetarian Sattvic gourmet dining curated for pilgrims.',
      images: [
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
      ],
      amenities: [
        'Free Temple Escort & VIP Pass Assistance',
        'Pure Sattvic & Jain Vegetarian Kitchen',
        'Private Bajra Ghat Boat Service',
        'Morning Vedic Yoga & Meditation Terrace',
        'High-Speed Wi-Fi & Concierge Desk',
        'Ayurvedic Wellness Spa & Abhyanga',
        '24/7 Hot Water & Power Backup',
        'In-Room Puja Thali & Gangajal Amenities',
      ],
      basePrice: 16500,
      isTopRated: true,
      rooms: [
        {
          id: 'room-brij-1',
          hotelId: 'htl-varanasi-1',
          name: 'Maharaja Ghat View Luxury Suite',
          roomOnlyPrice: 16500,
          breakfastPrice: 18200,
          halfBoardPrice: 20500,
          fullBoardPrice: 22800,
          imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=600&q=80',
          bedType: '1 King Bed (Riverview Balcony)',
          capacity: '2 Adults, 1 Child',
        },
        {
          id: 'room-brij-2',
          hotelId: 'htl-varanasi-1',
          name: 'Darbhanga Heritage Deluxe Room',
          roomOnlyPrice: 12900,
          breakfastPrice: 14400,
          halfBoardPrice: 16200,
          fullBoardPrice: 18000,
          imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=600&q=80',
          bedType: '1 Queen Bed or 2 Twin Beds',
          capacity: '2 Adults',
        },
      ],
    },
    {
      id: 'htl-varanasi-2',
      cityId: 'city-varanasi',
      cityName: 'Varanasi',
      name: 'Taj Ganges - Spiritual Oasis & Lush Gardens',
      starRating: 5,
      googleRating: 4.8,
      reviewCount: 2310,
      address: 'Nadesar Palace Grounds, Raja Bazaar Road, Varanasi 221002',
      distanceToTemple: '3.8 km to Kashi Vishwanath (Complimentary Shuttle)',
      darshanType: 'VIP Darshan Concierge Desk',
      description: 'Set amidst 12 acres of tranquil manicured gardens, Taj Ganges is a peaceful sanctuary for pilgrims and leisure travelers. Featuring serene poolside lounges, round-the-clock spiritual travel desk, exquisite vegetarian culinary options, and plush modern comforts.',
      images: [
        'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80',
      ],
      amenities: [
        'Complimentary Temple Shuttle to Godowlia',
        'Jiva Ayurvedic Spa & Steam',
        '24-Hour Room Service',
        'Special Fasting & Navratri Thali on Request',
        'Swimming Pool & Fitness Center',
        'Large Family Interconnecting Suites',
      ],
      basePrice: 9800,
      isTopRated: true,
      rooms: [
        {
          id: 'room-taj-1',
          hotelId: 'htl-varanasi-2',
          name: 'Executive Garden Facing Deluxe',
          roomOnlyPrice: 9800,
          breakfastPrice: 11200,
          halfBoardPrice: 13000,
          fullBoardPrice: 14800,
          imageUrl: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=600&q=80',
          bedType: '1 King Bed',
          capacity: '2 Adults, 2 Children',
        },
      ],
    },
    {
      id: 'htl-ayodhya-1',
      cityId: 'city-ayodhya',
      cityName: 'Ayodhya',
      name: 'The Ramayana Royal Retreat - Steps from Ram Mandir',
      starRating: 4,
      googleRating: 4.8,
      reviewCount: 980,
      address: 'Ram Path, Near Hanumangarhi & Ram Janmabhoomi, Ayodhya 224123',
      distanceToTemple: '450m from Shri Ram Janmabhoomi Main Gate',
      darshanType: 'Direct Walking Path to Sugriva Qila & Mandir',
      description: 'The premier luxury pilgrim hotel right on Ram Path. Designed in classic Awadhi & Vedic temple stone architecture with brass accents, devotional morning shehnai chimes, and dedicated assistance for Sugriva Qila and Ram Janmabhoomi Darshan.',
      images: [
        'https://images.unsplash.com/photo-1596436889106-be35e843f974?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80',
      ],
      amenities: [
        'Walkable to Ram Janmabhoomi & Hanumangarhi',
        '100% Pure Vegetarian & Onion-Garlic Free Options',
        'Complimentary Golf Cart transfers for Senior Pilgrims',
        'Saryu Maha Aarti Evening Escort',
        'Doctor-on-Call & Oxygen Support Available',
        'Spacious Wheelchair Accessible Rooms',
      ],
      basePrice: 6500,
      isTopRated: true,
      rooms: [
        {
          id: 'room-ram-1',
          hotelId: 'htl-ayodhya-1',
          name: 'Shri Ram Deluxe Sanctum Room',
          roomOnlyPrice: 6500,
          breakfastPrice: 7400,
          halfBoardPrice: 8500,
          fullBoardPrice: 9600,
          imageUrl: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=600&q=80',
          bedType: '1 King Bed or 2 Twin Beds',
          capacity: '2 Adults, 1 Child',
        },
        {
          id: 'room-ram-2',
          hotelId: 'htl-ayodhya-1',
          name: 'Family Yatra Suite (Quad Sharing)',
          roomOnlyPrice: 9900,
          breakfastPrice: 11500,
          halfBoardPrice: 13200,
          fullBoardPrice: 14900,
          imageUrl: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=600&q=80',
          bedType: '2 King Beds',
          capacity: '4 Adults',
        },
      ],
    },
    {
      id: 'htl-kedarnath-1',
      cityId: 'city-kedarnath',
      cityName: 'Kedarnath',
      name: 'Himalayan Nirvana Grand & Alpine Cottages',
      starRating: 4,
      googleRating: 4.7,
      reviewCount: 620,
      address: 'Near Helipad & Temple Base Path, Kedarnath Valley, Guptkashi - Kedarnath 246471',
      distanceToTemple: '250m from Kedarnath Temple Outer Gate',
      darshanType: 'Walking proximity with Thermal Heated Rooms',
      description: 'Specially insulated high-altitude sanctuary with central heating, 24-hour hot water, and in-house oxygen cylinders. Ideal for pilgrims seeking safety, comfort, and immediate access to Lord Kedarnath Jyotirlinga for early morning Aarti.',
      images: [
        'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1586611292717-f828b167408c?auto=format&fit=crop&w=800&q=80',
      ],
      amenities: [
        'Heavy-Duty Room Heating & Thermal Blankets',
        'Continuous Hot Water Geysers',
        'Medical Emergency Oxygen Station',
        'Helicopter Shuttle Assistance & Pithu/Pony Booking',
        'Hot Herbal Kadha & Nutritious Sattvic Meals',
      ],
      basePrice: 8500,
      isTopRated: true,
      rooms: [
        {
          id: 'room-kdr-1',
          hotelId: 'htl-kedarnath-1',
          name: 'Heated Mountain View Alpine Cottage',
          roomOnlyPrice: 8500,
          breakfastPrice: 9400,
          halfBoardPrice: 10600,
          fullBoardPrice: 11800,
          imageUrl: 'https://images.unsplash.com/photo-1586611292717-f828b167408c?auto=format&fit=crop&w=600&q=80',
          bedType: '2 Double Beds with Warm Quilts',
          capacity: '2-4 Guests',
        },
      ],
    },
    {
      id: 'htl-tirupati-1',
      cityId: 'city-tirupati',
      cityName: 'Tirupati',
      name: 'Marasa Sarovar Premiere - Dasavatara Sacred Theme',
      starRating: 5,
      googleRating: 4.8,
      reviewCount: 3100,
      address: 'Upadhyaya Nagar, Karakambadi Road, Tirupati, Andhra Pradesh 517507',
      distanceToTemple: '15 mins drive to Alipiri Footpath Gate & Ghat Road',
      darshanType: 'Special Entry Seeghra Darshan Assistance',
      description: 'The world’s first theme hotel inspired by the 10 Avatars of Lord Vishnu. Architecturally unique with lotus pond pavilions, pure vegetarian South and North Indian restaurants (Thali & Krishna Vihar), and hassle-free Tirumala hilltop logistics.',
      images: [
        'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
      ],
      amenities: [
        'Tirumala Hilltop Private AC Cab Coordination',
        'Authentic Tirupati Laddu Prasadam on Check-in',
        'Two Multi-Cuisine Sattvic Restaurants',
        'Swimming Pool & Ayurvedic Rejuvenation Spa',
        'Luggage Safe Keep during Hilltop Yatra',
      ],
      basePrice: 5900,
      isTopRated: true,
      rooms: [
        {
          id: 'room-mar-1',
          hotelId: 'htl-tirupati-1',
          name: 'Matsya Premium Pool & Hill View',
          roomOnlyPrice: 5900,
          breakfastPrice: 6800,
          halfBoardPrice: 7900,
          fullBoardPrice: 8900,
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=600&q=80',
          bedType: '1 King Bed or Twin Beds',
          capacity: '2 Adults, 1 Child',
        },
      ],
    },
    {
      id: 'htl-puri-1',
      cityId: 'city-puri',
      cityName: 'Puri',
      name: 'Mayfair Waves - Seafront Sanctum near Jagannath Temple',
      starRating: 5,
      googleRating: 4.8,
      reviewCount: 2200,
      address: 'Chakratirtha Road, Puri Sea Beach, Puri, Odisha 752002',
      distanceToTemple: '2.2 km to Lord Jagannath Temple',
      darshanType: 'Panda / Priest Accompanied VIP Darshan Assistance',
      description: 'Luxury seafront retreat offering pristine views of the Bay of Bengal and effortless access to Sri Mandir. Renowned for its hospitality, authentic Odia temple cuisine, and soothing coastal breeze after an enriching darshan.',
      images: [
        'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1563911302283-d2bc129e7570?auto=format&fit=crop&w=800&q=80',
      ],
      amenities: [
        'Private Beach Access & Oceanview Sunbeds',
        'Direct Panda Priest Coordination for Mahaprasad',
        'Jagannath Temple Car Pickup & Drop',
        'Swimming Pool & Spa Therapy',
        'Multi-Cuisine Fine Dining & Sattvic Options',
      ],
      basePrice: 8200,
      isTopRated: true,
      rooms: [
        {
          id: 'room-may-1',
          hotelId: 'htl-puri-1',
          name: 'Sea Facing Deluxe Wave Room',
          roomOnlyPrice: 8200,
          breakfastPrice: 9300,
          halfBoardPrice: 10600,
          fullBoardPrice: 11900,
          imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=600&q=80',
          bedType: '1 King Bed with Balcony',
          capacity: '2 Adults, 1 Child',
        },
      ],
    },
    {
      id: 'htl-rishikesh-1',
      cityId: 'city-rishikesh',
      cityName: 'Rishikesh & Haridwar',
      name: 'Ganga Kinare - A Riverside Heritage Boutique Resort',
      starRating: 4,
      googleRating: 4.8,
      reviewCount: 1890,
      address: '237 Virbhadra Road, Barrage Road, Rishikesh, Uttarakhand 249201',
      distanceToTemple: 'Direct private ghat on River Ganga',
      darshanType: 'Private Evening Ganga Aarti on Hotel Ghat',
      description: 'Perched on the holy banks of Mother Ganga, Ganga Kinare is the only boutique hotel in Rishikesh with its own serene private riverfront ghat. Experience sunrise yoga, riverside meditation, Ayurvedic wellness, and evening Aarti away from the bustling crowds.',
      images: [
        'https://images.unsplash.com/photo-1600100397608-f010f443bbf6?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=800&q=80',
      ],
      amenities: [
        'Private Ganga Riverfront Ghat & Daily Aarti',
        'Daily Morning Hatha Yoga & Guided Meditation',
        'Ayurveda Spa & Detox Panchakarma',
        'Jal & Jalebi Specialty Pure Veg Restaurant',
        'Bicycle Tours along the Sacred Canal',
      ],
      basePrice: 6200,
      isTopRated: true,
      rooms: [
        {
          id: 'room-gng-1',
          hotelId: 'htl-rishikesh-1',
          name: 'Lotus Holy Ganga View Deluxe',
          roomOnlyPrice: 6200,
          breakfastPrice: 7100,
          halfBoardPrice: 8300,
          fullBoardPrice: 9400,
          imageUrl: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=600&q=80',
          bedType: '1 King Bed',
          capacity: '2 Adults, 1 Child',
        },
      ],
    },
  ];

  const packages: Package[] = [
    {
      id: 'pkg-chardham-1',
      title: 'Sacred Char Dham Yatra: Yamunotri, Gangotri, Kedarnath & Badrinath',
      location: 'Haridwar • Barkot • Uttarkashi • Guptkashi • Kedarnath • Badrinath',
      duration: '9 Nights 10 Days',
      bookedRank: '#1 Most Booked Spiritual Yatra',
      imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1600100397608-f010f443bbf6?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1586611292717-f828b167408c?auto=format&fit=crop&w=800&q=80',
      ],
      startingPrice: 38500,
      category: 'Char Dham',
      packageType: 'Complete All-Inclusive Pilgrimage',
      experienceLevel: 'Moderate • Fully Guided with Medical Support',
      hotelsLevel: '3 & 4 Star Deluxe Pilgrim Stays + Heated Kedarnath Cottages',
      transfers: 'AC Tempo Traveler / Innova Crysta & Helicopter Priority Passes',
      overview: 'Embark on the ultimate soul-cleansing spiritual journey across the four holy Himalayan dhams. Beginning with the holy dips at Haridwar, proceed to the origins of the Yamuna and Ganga rivers, conquer the sublime heights of Kedarnath Jyotirlinga nestled below snowy peaks, and receive blessings at Badrivishal in the Nar-Narayan valley. Our enterprise itinerary guarantees premium stays, bio-oxygen cylinders, senior pilgrim assistance, and verified VIP temple entries.',
      highlights: [
        'VIP Darshan coordination at Kedarnath & Badrinath temples',
        'Helicopter ticket assistance for Phata/Sersi/Guptkashi route',
        'Comfortable heated rooms in high-altitude zones',
        'Dedicated knowledgeable Pandit & Pilgrimage Coordinator throughout',
        'All Sattvic vegetarian buffet meals (Breakfast, Lunch & Dinner)',
        'Emergency oxygen support kits & 24x7 medical emergency on-call',
        'Evening Ganga Aarti experience at Har Ki Pauri Haridwar',
      ],
      cancellationPolicy: 'Full refund if cancelled 30 days prior to departure. 50% refund between 15-29 days. Date rescheduling is free up to 14 days before journey subject to availability.',
      itinerary: [
        { day: 1, title: 'Arrival in Haridwar / Dehradun - Ganga Aarti at Har Ki Pauri', desc: 'Warm reception by our tour manager, check-in to deluxe hotel, evening VIP seating for Maha Ganga Aarti.' },
        { day: 2, title: 'Haridwar to Barkot via Mussoorie & Kempty Falls', desc: 'Scenic mountain drive through Garhwal hills. Overnight stay at scenic valley cottages in Barkot.' },
        { day: 3, title: 'Barkot to Yamunotri Dham Trek & Return to Barkot', desc: 'Early morning drive to Janki Chatti. Holy dip in Surya Kund, Divya Shila puja, and darshan of Goddess Yamunotri.' },
        { day: 4, title: 'Barkot to Uttarkashi - Kashi Vishwanath Mandir', desc: 'Drive alongside Bhagirathi river, visit ancient Kashi Vishwanath temple and Shakti Mandir in Uttarkashi.' },
        { day: 5, title: 'Uttarkashi to Gangotri Dham & back to Uttarkashi', desc: 'Sublime drive through Harsil Valley. Darshan at Bhagirath Shila and holy bath in Bhagirathi.' },
        { day: 6, title: 'Uttarkashi to Guptkashi / Phata Base', desc: 'Scenic travel across Mandakini Valley. Medical checkup and briefing for Kedarnath ascent.' },
        { day: 7, title: 'Guptkashi to Kedarnath Dham - Evening Divine Aarti', desc: 'Ascent via helicopter or assisted trek. Check-in to heated cottage, attend glorious evening Aarti in front of Kedarnath spire.' },
        { day: 8, title: 'Kedarnath to Badrinath Dham via Chopta & Joshimath', desc: 'Morning Maha Abhishek darshan at Kedarnath, descent to base, scenic transit to Badrinath via Valley of Chopta.' },
        { day: 9, title: 'Badrinath Darshan, Mana Village & Drive to Rudraprayag', desc: 'Holy dip in Tapt Kund, Badrinath darshan, visit India’s last village Mana, Vyas Gufa, and Saraswati Udgam.' },
        { day: 10, title: 'Rudraprayag to Rishikesh / Dehradun Departure', desc: 'Visit Devprayag Sangam (confluence of Alaknanda and Bhagirathi), Lakshman Jhula in Rishikesh, and departure transfers.' },
      ],
    },
    {
      id: 'pkg-kashi-ayodhya-1',
      title: 'Divya Uttar Pradesh: Varanasi, Ayodhya & Prayagraj Sangam Trail',
      location: 'Varanasi • Prayagraj • Ayodhya • Sarnath',
      duration: '4 Nights 5 Days',
      bookedRank: 'Top Rated Cultural Pilgrimage',
      imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1706857053427-4c3e8006bbca?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
      ],
      startingPrice: 18900,
      category: 'Varanasi Ayodhya',
      packageType: 'Heritage & Spiritual Discovery',
      experienceLevel: 'Easy & Relaxed • Senior Friendly',
      hotelsLevel: '4 & 5 Star Heritage Stays',
      transfers: 'Private Chauffeur Driven AC Innova Crysta',
      overview: 'Experience the golden triad of Sanatana Dharma. Witness the eternal mysticism of Kashi Vishwanath Corridor, cruise the sunlit Ganga ghats on a private wooden Bajra, take a purifying holy dip at the Triveni Sangam in Prayagraj, and behold the magnificent grand Shri Ram Janmabhoomi Mandir and Hanumangarhi in Ayodhya.',
      highlights: [
        'VIP Sugam Darshan entry at Kashi Vishwanath Temple',
        'Private vintage Bajra boat ride during sunrise & evening Dashashwamedh Aarti',
        'Special escorted darshan at Shri Ram Janmabhoomi & Hanumangarhi in Ayodhya',
        'Boat ride to Triveni Sangam point with holy snan priest services',
        'All deluxe hotel accommodations with daily buffet breakfast & dinner',
        'Excursion to Sarnath - Buddha Deer Park & Dhamek Stupa',
      ],
      cancellationPolicy: '100% refund up to 14 days before start date. 50% refund up to 7 days before start date.',
      itinerary: [
        { day: 1, title: 'Arrival in Varanasi - Evening Grand Ganga Aarti', desc: 'Airport pickup, check-in to heritage riverside hotel, evening private boat for Dashashwamedh Aarti.' },
        { day: 2, title: 'Kashi Vishwanath Corridor, Annapurna, & Sarnath', desc: 'Early morning Mangala Aarti / VIP darshan at Kashi Vishwanath, Kal Bhairav, and afternoon visit to Sarnath.' },
        { day: 3, title: 'Varanasi to Prayagraj Sangam & Drive to Ayodhya', desc: 'Drive to holy Prayagraj, boat to Triveni Sangam, visit Anand Bhavan and Bade Hanuman Ji, continue to Ayodhya.' },
        { day: 4, title: 'Full Day Ayodhya Darshan - Ram Mandir & Saryu Aarti', desc: 'Comprehensive guided darshan at Ram Janmabhoomi, Kanak Bhavan, Hanumangarhi, and sunset Aarti at Saryu Ghat.' },
        { day: 5, title: 'Ayodhya / Varanasi Departure', desc: 'Morning souvenir shopping (Banarasi silk / Ayodhya sacred sweets) and transfer to Ayodhya (AYJ) or Varanasi (VNS) airport.' },
      ],
    },
    {
      id: 'pkg-south-1',
      title: 'Grand South India Temple Circuit: Tirupati, Rameshwaram & Madurai',
      location: 'Chennai • Tirupati • Kanchipuram • Madurai • Rameshwaram • Kanyakumari',
      duration: '6 Nights 7 Days',
      bookedRank: 'Highest Customer Satisfaction',
      imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1621847468516-1ed5d0df56fe?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
      ],
      startingPrice: 27500,
      category: 'South India',
      packageType: 'Dravidian Temple Grandeur',
      experienceLevel: 'Comfortable • Family & Senior Friendly',
      hotelsLevel: '4 & 5 Star Premium Stays',
      transfers: 'Luxury AC Bus or Private Innova Vehicle',
      overview: 'Traverse the majestic soaring gopurams and sacred waters of South India. Receive divine darshan of Lord Venkateswara at Tirumala with pre-booked Special Entry, explore the silk temple city of Kanchipuram, witness Meenakshi Amman’s evening celestial wedding in Madurai, take a holy bath in the 22 sacred teerthams of Ramanathaswamy, and stand at the confluence of three oceans at Kanyakumari.',
      highlights: [
        'Pre-booked Special Entry Tirupati Balaji Darshan ticket & Tirumala transportation',
        'Guided holy Snan ritual across 22 sacred wells at Rameshwaram Jyotirlinga',
        'Visit Ram Setu / Dhanushkodi ghost town viewpoint',
        'VIP Darshan at Madurai Meenakshi Amman Temple',
        'Spectacular sunrise & sunset views over Triveni Sangam in Kanyakumari',
      ],
      cancellationPolicy: 'Free cancellation up to 21 days prior to departure date.',
      itinerary: [
        { day: 1, title: 'Arrival Chennai - Drive to Tirupati & Padmavathi Temple', desc: 'Airport welcome, drive to Tirupati foothills, evening visit to Sri Padmavathi Ammavari Temple.' },
        { day: 2, title: 'Tirumala Balaji Special Entry Darshan & Kanchipuram', desc: 'Morning ascent to Tirumala for divine darshan of Sri Venkateswara Swamy, afternoon transit to Kanchipuram.' },
        { day: 3, title: 'Kanchipuram Temples to Madurai by Superfast Train / AC Vehicle', desc: 'Visit Ekambareswarar and Kailasanathar temples, transit to the ancient cultural capital of Madurai.' },
        { day: 4, title: 'Madurai Meenakshi Temple & Drive to Rameshwaram Island', desc: 'Darshan of Goddess Meenakshi, drive across Pamban Sea Bridge into holy Rameshwaram island.' },
        { day: 5, title: 'Rameshwaram 22 Teerthams, Ramanathaswamy & Dhanushkodi', desc: 'Morning sacred holy bath in 22 wells, Jyotirlinga Abhishek, afternoon visit to Dhanushkodi and Ram Setu.' },
        { day: 6, title: 'Rameshwaram to Kanyakumari - Ocean Confluence', desc: 'Drive to southern tip of India, ferry to Vivekananda Rock Memorial and Thiruvalluvar Statue.' },
        { day: 7, title: 'Sunrise over Ocean & Departure via Trivandrum Airport', desc: 'Mesmerizing 3-ocean sunrise view, checkout, transfer to Trivandrum (TRV) International Airport.' },
      ],
    },
    {
      id: 'pkg-jyotirlinga-1',
      title: 'Maha Jyotirlinga Darshan: Mahakaleshwar, Omkareshwar & Somnath',
      location: 'Indore • Ujjain • Omkareshwar • Ahmedabad • Dwarka • Somnath',
      duration: '7 Nights 8 Days',
      bookedRank: 'Divine Jyotirlinga Special',
      imageUrl: 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1200&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=800&q=80',
      ],
      startingPrice: 31900,
      category: 'Jyotirlinga',
      packageType: 'Sacred Shiva & Krishna Pilgrimage',
      experienceLevel: 'Comfortable',
      hotelsLevel: 'Deluxe & Luxury Hotels',
      transfers: 'Dedicated Private AC Vehicle & Flight Connectivity',
      overview: 'A profound pilgrimage connecting Lord Shiva’s greatest Jyotirlingas with Lord Krishna’s sacred kingdom of Dwarka. Experience the intense mysticism of the 4 AM Bhasma Aarti at Mahakaleshwar in Ujjain, circumambulate the Om-shaped island of Omkareshwar on River Narmada, visit Dwarkadhish temple and Bet Dwarka, and witness the sea-kissed first Jyotirlinga at Somnath.',
      highlights: [
        'Guaranteed Bhasma Aarti registration assistance at Mahakaleshwar Ujjain',
        'Boat ride around Mandhata Island at Omkareshwar on Holy Narmada',
        'Dwarkadhish temple flag changing (Dhwajaji) ceremony darshan',
        'Somnath Temple Sound & Light Laser Show against ocean waves',
        'Visit Nageshwar Jyotirlinga, Rukmini Temple & Bet Dwarka',
      ],
      cancellationPolicy: 'Refundable with nominal 10% processing charge up to 20 days prior.',
      itinerary: [
        { day: 1, title: 'Arrival Indore - Transfer to Sacred Ujjain & Mahakal Lok', desc: 'Pickup from Indore airport, drive to Ujjain, evening stroll through the grand Mahakal Lok corridor.' },
        { day: 2, title: 'Early Morning Bhasma Aarti & Omkareshwar Island', desc: 'Attend the divine 4 AM Bhasma Aarti, visit Kal Bhairav temple, drive to Omkareshwar for Narmada snan.' },
        { day: 3, title: 'Omkareshwar to Indore & Flight / Train to Ahmedabad / Rajkot', desc: 'Morning Narmada Aarti, transit to airport/station for journey towards Gujarat yatra hub.' },
        { day: 4, title: 'Drive to Dwarka - Evening Dwarkadhish Darshan', desc: 'Scenic highway journey to holy Dwarka. Attend evening Sandhya Aarti at the 2500-year-old Jagat Mandir.' },
        { day: 5, title: 'Bet Dwarka, Nageshwar Jyotirlinga & Gopi Talav', desc: 'Ferry to island of Bet Dwarka, darshan of Nageshwar (one of 12 Jyotirlingas), and Rukmini Devi temple.' },
        { day: 6, title: 'Dwarka to Porbandar & Holy Somnath Temple', desc: 'Visit Kirti Mandir and Sudama Temple at Porbandar, arrive in Somnath for evening Aarti and Laser Light Show.' },
        { day: 7, title: 'Somnath Abhishek, Bhalka Teerth & Rajkot', desc: 'Early morning oceanview Abhishek at Somnath, visit Bhalka Teerth (Lord Krishna Dehotsarg), drive to Rajkot.' },
        { day: 8, title: 'Rajkot / Ahmedabad Departure', desc: 'Shopping for traditional handicrafts and departure flight from Rajkot or Ahmedabad.' },
      ],
    },
  ];

  const inquiries: Inquiry[] = [
    {
      id: 'inq-101',
      userId: 'usr-demo-1',
      type: 'HOTEL',
      referenceId: 'htl-varanasi-1',
      referenceName: 'BrijRama Palace - Heritage Grand on Darbhanga Ghat',
      title: 'BrijRama Palace - Heritage Grand on Darbhanga Ghat',
      fullName: 'Rohan Sharma',
      customerName: 'Rohan Sharma',
      email: 'rohan.sharma@example.com',
      customerEmail: 'rohan.sharma@example.com',
      whatsappNumber: '+91 98765 43210',
      customerPhone: '+91 98765 43210',
      userCity: 'New Delhi',
      checkInDate: '2026-10-15',
      guests: 3,
      adults: 3,
      children: 0,
      planChosen: 'With Breakfast',
      selectedPlan: 'With Breakfast',
      specialRequests: 'Senior parents traveling for Kashi Vishwanath Darshan; requesting ground floor room & wheelchair assistance.',
      status: 'NEW',
      isResolved: false,
      createdAt: '2026-08-25T14:20:00.000Z',
    },
    {
      id: 'inq-102',
      type: 'PACKAGE',
      referenceId: 'pkg-chardham-1',
      referenceName: 'Sacred Char Dham Yatra: Yamunotri, Gangotri, Kedarnath & Badrinath',
      title: 'Sacred Char Dham Yatra: Yamunotri, Gangotri, Kedarnath & Badrinath',
      fullName: 'Sunita Mehra',
      customerName: 'Sunita Mehra',
      email: 'sunita.mehra@gmail.com',
      customerEmail: 'sunita.mehra@gmail.com',
      whatsappNumber: '+91 98112 34567',
      customerPhone: '+91 98112 34567',
      userCity: 'Mumbai',
      checkInDate: '2026-09-20',
      guests: 4,
      adults: 4,
      children: 0,
      planChosen: 'Helicopter All-Inclusive',
      selectedPlan: 'Helicopter All-Inclusive',
      specialRequests: 'Need 2 twin rooms and priority helicopter passes for Kedarnath for elderly family members.',
      status: 'CONFIRMED',
      isResolved: true,
      createdAt: '2026-08-20T09:15:00.000Z',
    },
    {
      id: 'inq-103',
      type: 'HOTEL',
      referenceId: 'htl-ayodhya-1',
      referenceName: 'The Ramayana Royal Retreat - Steps from Ram Mandir',
      title: 'The Ramayana Royal Retreat - Steps from Ram Mandir',
      fullName: 'Vikramaditya Rao',
      customerName: 'Vikramaditya Rao',
      email: 'v.rao@yahoo.com',
      customerEmail: 'v.rao@yahoo.com',
      whatsappNumber: '+91 94440 12890',
      customerPhone: '+91 94440 12890',
      userCity: 'Bengaluru',
      checkInDate: '2026-11-04',
      guests: 2,
      adults: 2,
      children: 0,
      planChosen: 'Half Board',
      selectedPlan: 'Half Board',
      specialRequests: 'Celebrating 25th wedding anniversary with special puja at Ram Mandir.',
      status: 'CONTACTED',
      isResolved: false,
      createdAt: '2026-08-28T18:45:00.000Z',
    },
  ];

  const reviews: Review[] = [
    {
      id: 'rev-1',
      authorName: 'Milind Pawarc',
      authorLocation: 'Mathura · Vrindavan',
      authorInitials: 'MP',
      rating: 5.0,
      reviewText: 'We arranged a 3-day spiritual tour for our family to Mathura and Vrindavan. TirthYatraTrails ensured our hotel was barely 5 minutes from Banke Bihari and Prem Mandir. The morning temple transfer, clean Sattvic dining, and dedicated tour manager made our darshan utterly blissful without any stress.',
      destinationImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80',
      isVerified: true,
      googleReviewUrl: 'https://maps.google.com/?q=Vrindavan+Temples',
      isFeatured: true,
      order: 1,
      createdAt: '2026-08-15T10:00:00.000Z',
    },
    {
      id: 'rev-2',
      authorName: 'Ramesh & Sunita Sharma',
      authorLocation: 'Kashi · Ayodhya',
      authorInitials: 'RS',
      rating: 5.0,
      reviewText: 'We arranged a 6-day pilgrimage for our elderly parents to Kashi Vishwanath and Ayodhya Ram Mandir. TirthYatraTrails managed everything with utmost devotion — wheelchair assistance was waiting right at the ghats, our hotel was 4 minutes from the sanctum gate, and the kitchen prepared pure Jain-Sattvic meals daily. Having a dedicated 24x7 travel desk gave our entire family complete peace of mind.',
      destinationImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80',
      isVerified: true,
      googleReviewUrl: 'https://maps.google.com/?q=Kashi+Vishwanath',
      isFeatured: true,
      order: 2,
      createdAt: '2026-08-10T14:30:00.000Z',
    },
    {
      id: 'rev-3',
      authorName: 'Ananya Raghavan',
      authorLocation: 'Tirupati Balaji',
      authorInitials: 'AR',
      rating: 5.0,
      reviewText: 'Booking the Special Entry Darshan pass and hillside accommodation through TirthYatraTrails was seamless. From Chennai airport cab pickup to the Tirumala hilltop cottage, everything was timely and respectful of traditional rituals. Truly exceptional service.',
      destinationImage: 'https://images.unsplash.com/photo-1621847468516-1ed5d0df56fe?auto=format&fit=crop&w=1200&q=80',
      isVerified: true,
      googleReviewUrl: 'https://maps.google.com/?q=Tirupati+Balaji',
      isFeatured: true,
      order: 3,
      createdAt: '2026-08-01T09:15:00.000Z',
    },
  ];

  return { users, cities, hotels, packages, inquiries, reviews };
}
